/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoginIntoSystem;
import java.sql.*;
import javax.swing.JOptionPane;
import CanteenAutomationSystem.CanteenSystem;

/**
 *
 * @author Rohan
 */
public class Login extends javax.swing.JFrame {
 
      public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextpassword = new javax.swing.JTextField();
        jTextusername = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtnSubmit = new javax.swing.JButton();
        password = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        username1 = new javax.swing.JTextField();
        password1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(3276, 3276));

        jPanel2.setLayout(null);

        jPanel4.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Username");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(10, 11, 78, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Password");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(10, 106, 74, 22);

        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(80, 180, 100, 23);
        jPanel4.add(jTextpassword);
        jTextpassword.setBounds(152, 109, 92, 30);
        jPanel4.add(jTextusername);
        jTextusername.setBounds(152, 11, 92, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rohan\\Desktop\\Canteen_php\\sign up.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(0, 0, 290, 230);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(50, 80, 280, 230);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rohan\\Desktop\\Canteen_php\\sign up2.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, 0, 360, 340);

        jTabbedPane1.addTab("Sign Up", jPanel2);

        jPanel1.setLayout(null);

        jPanel3.setLayout(null);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASSWORD");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 72, 90, 14);
        jPanel3.add(username);
        username.setBounds(111, 11, 91, 20);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USERNAME");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 20, 80, 14);

        BtnSubmit.setBackground(new java.awt.Color(51, 51, 255));
        BtnSubmit.setText("SUBMIT");
        BtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubmitActionPerformed(evt);
            }
        });
        jPanel3.add(BtnSubmit);
        BtnSubmit.setBounds(50, 130, 110, 23);
        jPanel3.add(password);
        password.setBounds(111, 69, 91, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rohan\\Desktop\\Canteen_php\\login.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(0, 0, 210, 160);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(72, 84, 0, 0);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("USERNAME");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 90, 80, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("PASSWORD");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 140, 80, 17);
        jPanel1.add(username1);
        username1.setBounds(200, 90, 90, 20);
        jPanel1.add(password1);
        password1.setBounds(200, 150, 90, 20);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(110, 200, 110, 31);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("ADMIN?");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 280, 110, 20);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("ADMIN LOGIN");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(150, 280, 120, 25);

        jTabbedPane1.addTab("Login", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubmitActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_BtnSubmitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String user= jTextusername.getText();
        String pass=jTextpassword.getText();
        try{
        //loading drivers for mysql
        Connection conn;
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/canteen","root",""); 
        //PreparedStatement pst=conn.prepareStatement("insert into login values ('"+jTextusername.getText()+"','"+Integer.valueOf(jTextpassword.getText()));
        PreparedStatement pst=conn.prepareStatement("INSERT INTO login (USERNAME, PASSWORD) VALUES "+"('"+user+"','"+pass+"')");
        
        int i=pst.executeUpdate();
        
          if(i==1)
          {
            JOptionPane.showMessageDialog(null, "You are Registered");
            this.dispose();
          }
        
        }
        catch(Exception se)
        {
            se.printStackTrace();
        }
	
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
       Connection con;
       con = DriverManager.getConnection("jdbc:mysql://localhost:3306/canteen","root","");
       //Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
       //Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/canteen?zeroDateTimeBehavior=convertToNull","root","");    
       PreparedStatement ps = con.prepareStatement("SELECT PASSWORD FROM `login` WHERE `USERNAME`='"+username1.getText()+"'");
       ResultSet rs = ps.executeQuery();
       if(rs.next()) {
           if(rs.getString(1).equals(password1.getText())) {
               JOptionPane.showMessageDialog(null, "Accessed to database");
               dispose();
               CanteenSystem cs = new CanteenSystem();
               cs.setVisible(true);
           }
           else {
               JOptionPane.showMessageDialog(null, "Wrong Password");
           }
       }
       else {
           JOptionPane.showMessageDialog(null, "User not found");
       }
                
   }
   catch(Exception e){
       e.printStackTrace();
   }       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        Admin_Login admin=new Admin_Login();
        admin.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextpassword;
    private javax.swing.JTextField jTextusername;
    private javax.swing.JTextField password;
    private javax.swing.JTextField password1;
    private javax.swing.JTextField username;
    private javax.swing.JTextField username1;
    // End of variables declaration//GEN-END:variables
}